name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:

  build:
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}
    strategy:
      matrix:
        python-version: [3.9]
        torch-version: [2.2.0, "2.*"]
    container:
      image: python:${{ matrix.python-version }}
      options: --gpus all
    steps:
    - uses: actions/checkout@v4
    - name: Linting
      run: |
          pip install flake8==7.1.0 Flake8-pyproject black
          flake8 . --count --show-source --statistics
          black . --check
    - name: Install test dependencies
      env:
        TORCH: "${{ matrix.torch-version }}"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        # use CPU only on GH runner
        pip install torch==${TORCH} ${{ github.event.repository.private && '' || '-f https://download.pytorch.org/whl/cpu/torch_stable.html' }} --upgrade
        pip install h5py scikit-learn  # install packages that aren't required dependencies but that the tests do need        
        pip install --upgrade-strategy only-if-needed .
        pip install pytest
        pip install pytest-xdist[psutil]
    - name: Test with pytest
      run: |
        # See https://github.com/pytest-dev/pytest/issues/1075
        PYTHONHASHSEED=0 pytest -n auto tests/
